params = dict(state_dim=448,
              easy_mode=1000,
              easy_guess=1000,
              batch_size=500,
              critic_loss_weight=1,
              entropy_weight=0.1,
              mlp_lr=1e-4,
              transformer_lr=1e-5,
              char_logit=False,
              info_reward=False)
