params = dict(state_dim=448,
              embed_dim=128,
              easy_mode=100,
              easy_guess=100,
              batch_size=500,
              actor_lr=1e-4,
              critic_lr=1e-3,
              gamma=0.5,
              schedule_step_size= 3000,
              parallel_workers=4)
