params = dict(state_dim=448,
              embed_dim=32,
              easy_mode=2309,
              easy_guess=2309,
              batch_size=500,
              actor_lr=2.5e-5,
              critic_lr=2.5e-4,
              gamma=0.5,
              schedule_step_size= 3000,
              parallel_workers=4)
